/** Marquee strip — mirrors core positioning */
export const marqueeLabels = [
  "AI agents",
  "SaaS",
  "React Native",
  "Flutter",
  "iOS",
  "Android",
  "Desktop",
  "Windows",
  "macOS",
  "Linux",
  "Electron",
  "AWS",
  "React",
  "Node.js",
  "Microservices",
  "DevOps",
  "Managed services",
  "RPO",
  "Python",
  "Consulting",
  "ISO 9001",
] as const;
